# ----------------------------------------------------------------------------------------
#                             MEOW THEME CONFIGURATION
#                               Author: 小橘猫chanwj
#                  GITHUB: https://github.com/chanwj/hexo-theme-meow
#                  DOCUMENTATION: https://meow.jumaoo.top/categories/Docs文档
#                  PREVIEW STATION：https://meow.jumaoo.top
# ----------------------------------------------------------------------------------------

# Website Info
info:
  # Site Favicon
  favicon: assets/images/favicon.ico
  # Site Logo
  logo: assets/images/logo.png
  # Author Avatar
  avatar: assets/images/author.png
  # Datetime of when this website was built
  start_date: 2026-08-05 00:00:00 # Format should be as same as date_format and time_format of root config

# Theme Color & Mode
color:
  # Light Mode
  light:
    theme_color: '#1a1a1a'
  # Dark Mode
  dark:
    theme_color: '#88C0ED'
  # Light/Dark Mode Configuration
  mode:
    default: light # Default color mode, light or dark

# Global Configuration
global:
  # Icon Configuration
  icon:
    type: ta # Icon Style Type, uc or ta or other custom collection
  selectable: true # Whether users can select text
  # Change page title when page onblur, false or onblur title text
  onblur_title: "记得常来看看哦"
  mouse_click_style: true # Whether to display colorful heart when clicking

# Font Customization
font:
  custom: true # Whether to use custom font
  default_font_link: https://cdn.jsdelivr.net/npm/@chinese-fonts/syst@latest/dist/SourceHanSerifCN/result.css # Url of default font
  default_font_family: "'Source Han Serif CN VF', 'PingFang SC', 'Microsoft YaHei', serif" # Define default fonts
  title_font_link: # Url of title font
  title_font_family: "'vivo Sans', 'PingFang SC', 'Microsoft YaHei', Sans-serif, Serif" # Define title fonts
  code_font_link: assets/fonts/SFMonoRegular/result.css # Url of code font
  code_font_family: "'SF Mono', 'vivo Sans', 'PingFang SC', 'Microsoft YaHei', Courier, Consolas, Sans-serif" # Define code fonts

# Navigation Bar
menu:
  archives: /archives || ta-archive
  essay: /essay || ta-write
  categories: /categories || ta-category
  tags: /tags || ta-tag
  about: /posts/about/ || ta-about
  friends: /friends || ta-friend
  comments: /comments || ta-comment
  APP: /releases || ta-down

# Navigation Bar Configuration
menu_options:
  font_color: # Menu font color under light/dark mode
    light: '#4b4b4b'
    dark: '#bebec6'

# Search Function
search:
  enable: true # Whether to enable search function
  type: local # Search system type, support: local
  # Local Search
  local:
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Preload the search data when the page loads
    preload: true

# Banner Configuration
banner:
  # Background image of banner under light/dark mode
  image:
    light: assets/images/earth.webp
    dark: assets/images/sky.webp
    is_fixed: false # Whether the image is fixed as background or scrollable with banner at homepage, true or false
    position: center top # horizontal(left/center/right) vertical(top/center/bottom)
    repeat: no-repeat # repeat/repeat-x/repeat-y/no-repeat
  # Banner avatar (not at homepage)
  avatar:
    type: site # site(logo) or author(avatar) or false
    shape: 1 # Shape of avatar. 1(normal) or 2(circle)
    border: false # Whether to add border to avatar
  # Banner title
  title:
    enable: true # Whether to show title
    text: 「 溯月馆 」 # Title text
  # Banner subtitle at homepage
  subtitle:
    enable: true # Whether to show subtitle
    # Subtitle text (Data type: Array)
    text:
      - "探索科幻文学的边界"
    effect: true # Typewriter effect, true or false(only show the first text).
    type_speed: 100 # Typing speed (ms)
    back_speed: 150 # Backing speed (ms)
    start_delay: 500 # Start delay (ms)
    back_delay: 1500 # Backing delay (ms)
    loop: true # Whether to loop
    smart_backspace: true # Whether to enable smart backspace
    fade_out: true # Whether to enable fade out effect
    shuffle: false # Whether to shuffle the text list
  title_color: # Title color under light/dark mode
    light: '#fff'
    dark: '#e0e0e0'

# Sidebar At Homepage
sidebar:
  enable: true # Whether to show sidebar
  position: left # Sidebar position, left or right
  show_on_small_screen: true # Whether to show sidebar at the bottom of homepage on small screen
  # Information card
  info:
    enable: true # Whether to show information card
    type: author # Which type of avatar to show, site or author
    status: # Status next to the avatar
      emoji: 🤔 # false or emoji
      desc: "急头白脸开发博客中" # Describe the status
    link: /posts/about/ # Url for image clicking
    desc: "科幻爱好者，正在创作基于唯物史观的现实主义科幻系列《率月纪元》。" # Describe yourself or say something
    statistic: true # Whether to show the total number of articles, categories and tags
    social: # Social profiles
      enable: true # Whether to show social module
      list: # Social name: social icon || social link
        # email: brand-mail || contact@jumao.simplelogin.com
        # github: brand-github || https://github.com/chanwj
        email: brand-mail || tghyscifi@foxmail.com
        github: brand-github || https://github.com/tghyscifi
        bilibili: brand-bilibili || https://space.bilibili.com/400687907
        qq: brand-qq || https://qm.qq.com/q/TzJgjBrRGC
        qq-channel: brand-qq || https://pd.qq.com/s/1ve5ubxzj
        steam: brand-steam || https://steamcommunity.com/profiles/76561199032829132/
        rss: brand-rss || /atom.xml


  # Show announcement card, false or announcement text, markdown available
  announcement: |
    🤪急头白脸开发中，
    遇到问题请以任意方式向博主反馈。
  # Links card
  links:
    enable: true # Whether to show additional links
    title: 快速直达 # The title of links card
    list: # List of links. link name: url
      ℹ️关于本站: /posts/about/
      ⁉️最新动态: https://tghyscifi.github.io/essay
      📚《率月纪元》中心页: https://tghyscifi.github.io/posts/ratomoondp



  # Categories card
  categories:
    enable: true # Whether to show categories card
    depth: 2 # Levels of categories to be displayed. 0 displays all categories and child categories; 1 displays only top level categories. Better be 1~3.
    height: 190 # Inner height, number or stay blank (no limit)
  # Tags card
  tags:
    enable: true # Whether to show tags card
    height: # Inner height, number or stay blank (no limit)
  # Recent comments card
  recent_comments:
    enable: true # Whether to show recent comments card (waline required)
    count: 10 # Number of latest comments to display
    loop_time: 15s # Time for one loop (with unit: seconds)

# Floating Toolbar
toolbar:
  enable: true # Whether to show toolbar
  setting_enable: true # Whether to show setting button(color mode/font size/share)
  color_mode: true # Whether users can switch light/dark mode
  font_size_setting: true # Whether users can resize post font
  share: true # Whether to display share page button

# Homepage Customization
home:
  cover_position: left # Position of post cover, top or left

# Archive Customization
archive:
  icon:  # Show icon when no cover, icon link or stay blank
  thumbnail: true # Whether to show cover or photo

# Category Customization
category:
  depth: 0 # Levels of categories to be displayed. 0 displays all categories and child categories; 1 displays only top level categories. Max depth is 3
  fold: false # Whether to fold child categories by default

# Tags Customization
tag:
  style: 2 # 1: normal, 2: tagcloud
  show_count: true # Whether to show posts count of each tag
  color: true # Whether to apply font color to tags (tagcloud function)
  start_color: '#D3D3D3' # The lightest color of tags (tagcloud function)
  end_color: '#FFB347' # The darkest color of tags (tagcloud function)

# Posts Customization
post:
  excerpt_length: 120 # Max length of auto excerpt
  wordcount: true # Whether to show post wordcount
  # Reading time
  min2read:
    enable: true # Whether to show estimated reading time
    cn: 350 # Reading speed of Chinese
    en: 200 # Reading speed of English
  view: true # Whether to display post view data
  font_size: 20px # Font size of posts with unit
  font_size_small: 18px # Font size of posts with unit on small screen
  indent: false # Whether to indent the first line of paragraph in post by 2em
  # Post TOC module
  toc:
    enable: true # Whether to generate post TOC
    show: true # Whether to open post TOC automatically
    number: false # Whether to display TOC list number
    max_depth: 3 # Maximum heading depth of generated TOC
    max_items: Infinity # Maximum number of items in generated toc, Infinity or number
  # Post reward module
  reward:
    enable: false # Whether to show post reward module
    outer_text: # Text under reward button
    inner_text: # Text in reward module
    # Credits list
    reward_list:
      enable: true # Whether to show credits list link
      link: # Credits list link url
  # Post copyright module
  copyright:
    enable: true # Whether to show post copyright module
    type: 1 # Type of copyright. 1(license) or 2(custom)
    license: CC BY-NC-SA 4.0 # License type, usually use Creativecommons License
    license_link: https://creativecommons.org/licenses/by-nc-sa/4.0/ # Url of cc license
    license_desc: 'Attribution-NonCommercial-ShareAlike' # Description of cc license, display when hover
    custom_text: Only for reading, do NOT redistribute, remix, transform and build upon the material. # Description of custom copyright announcement
  tail_tags: true # Whether to show post's tags at the end of post content
  cover: true # Whether to display cover image in front of post content
  navigator: true # Whether to show previous post and next post.
  progress_bar: true # Whether to show post's reading progress bar on the top

# Image Configuration
image:
  image_caption: true # Whether to display image caption(alt text) in posts and pages
  loding_image: assets/images/loading.webp # Display loading image when target image is not loaded
  rounded_corners: true # Whether to display images with rounded corners

# Code Block
code:
  func: true # Whether to add function(copy&fold) to code block
  copy_with_text: false # Whether to attach copyright share text after clicking copy button (See share.share_text below)
  max_height: 22em # Max height of codeblock, false or height with unit
  # Color scheme for code highlighting
  theme:
    light: solar-flare-light # Light mode theme: solar-flare-light, panda-syntax-light
    dark: tomorrow-night # Dark mode theme: tomorrow-night, panda-syntax-dark

# Markdown Style
markdown:
  hr_icon: false # Icon display on horizontal rule, emoji or false

# Page View Counting
page_view:
  enable: true # Whether to show page view statistic
  url: https://cn.vercount.one/js # Counter API url
  site_pv: true # Site's page view
  site_uv: true # Site unique visitor
  page_pv: true # Page view

# Footer Customization
footer:
  icon: 😋 # Emoji or false
  author_link: /about # Url for the link of author
  runtime: true # Whether to show website running time
  statistic: true # Whether to show site statistics(total articles & total wordcount)
  # Site register info(e.g. ICP)
  register_info:
    enable: false # Whether to show register info
    record_info: 京ICP备………………号 # E.g. ICP record number
    query_url: https://beian.miit.gov.cn/ # E.g. ICP record url

# Reward Customization
reward:
  # QRcode list, false or QRcode title: QRcode image url
  qrcode: false
  # Text link list, false or Link title: link url
  link: false

# Share Customization
share:
  notify: false # Whether to enable notification when copy text(Ctrl+C) or pressing F12
  share_text: '' # Text attached to the copied information

# Essay Page
essay:
  desc: # Additional message of essay
  type: local # Essay type: local or artitalk
  # Artitalk config, https://artitalk.js.org/
  artitalk:
    app_id: # LeanCloud AppID
    app_key: # LeanCloud AppKey
    server_url: # API domain
    lang: zh-CN # Language, e.g. en, zh, es
    page_size: 5 # How many essay to be displayed when loaded
    avatar_pla: # Essay avatar url
    emoji: # Format in list: custom emoji name: custom emoji image url
    comment: 0 # Whether to enable comment function for each essay, 0(disable) or 1(enable)
  local:
    avatar_shape: 2 # Shape of avatar. 1(normal) or 2(circle)
    max_num: 30 # Max number of essays to display

# Friend Link Page
friends:
  desc: # Additional message of friends page

# Fiction Module
fiction:
  # Customize the display values of fiction attributes
  attribute:
    card_title: 作品信息 # Fiction Information
    addition_title: 注意 # Notice
    type: 类型 # Type
    fandom: 原作 # Fandom
    relationship: 关系 # Relationship
    character: 角色 # Character
    rating: 分级 # Rating
    warning: 预警 # Warning
    status: 状态 # Status
  # Customize the display values of fiction rating
  rating:
    -1: 未分级
    0: 全年龄 # General Audiences
    1: 青少年及以上 # Teen And Up Audiences
    2: 成人向 # Mature
    3: 成人级 # Explicit
  # Customize the display values of fiction statis
  status:
    Y: 已完结 # COMPLETE
    N: 未完待续…… # TO BE CONTINUED...

# Comment Module
comment:
  enable: true # Whether to enable comment module
  display: true # Whether to show comment module at posts automatically
  type: waline # Comment system, type: waline
  lazyload: true # Whether to load comment system when comment module enters the browser's viewport
  # Waline Config, https://waline.js.org/
  waline:
    server_url: https://comment.tghyscifi.cloud-ip.cc # Waline server URL, see more at https://waline.js.org/guide/
    lang: zh-CN # Language, e.g. zh-CN, en-US. https://waline.js.org/guide/features/i18n.html
    emoji:
      - 'https://registry.npmmirror.com/@waline/emojis/1.3.0/files/qq'
      - 'https://registry.npmmirror.com/@waline/emojis/1.3.0/files/tw-emoji' 
    # https://waline.js.org/guide/features/emoji.html
    reaction: # https://waline.js.org/guide/features/reaction.html
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/2764-fe0f.png' # ❤️
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f92f.png'      # 🤯
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f4a5.png'      # 💥
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1fae1.png'      # 🫡
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f602.png'      # 😂
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f914.png'      # 🤔
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f97a.png'      # 🥺
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f6a8.png'      # 🚨
      - 'https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/64/1f921.png'      # 🤡 
    option: # Custom other Waline options, https://waline.js.org/reference/client/props.html
      locale:
        placeholder: '欢迎评论～'
        reactionTitle: '点赞支持我吧！'
      commentSorting: 'hottest'
      requiredMeta: ['nick', 'mail'] 
  

# Album Module
album:
  local: false # Whether to enable local alubm (require image-size installed)

# Music Player Module
music:
  enable: true # Whether to enable global music player
  autoplay: false # Whether to play music automatically
  loop: all # How to loop music, all or one or none
  order: list # Play Music in which order, list or random
  volume: 0.5 # Default volume, 0-1
  lyric: true # Whether to display lyric
  meting: # Meting api config
    api: https://api.injahow.cn/meting/ # Custom Meting api url
    server: netease # Music platform: netease, tencent, kugou, xiami, baidu
    type: playlist # Audio type: song, playlist, album, search, artist
    id: "8197566341" # Audio source: song id / playlist id / album id / search keyword / artist

# CDN Configuration
cdn:
  # Whether to enable CDN
  enable: true
  # CDN provider
  provider: npmmirror # jsdelivr, unpkg, npmmirror, custom
  # Custom CDN url, should be formatted. Example: https://cdn.jsdelivr.net/npm/${name}@${version}/${path}
  custom:

# Whether to enable in-built 404 page
error_page: true